### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by jieglen** [mariostg/nffm#2]
I'm getting a compile time error using "make". I'm using Ubuntu Precise (12.04 LTS)

Output is:

```
nffm.o: In function `DoDirectoryList':
/src/nffm/nffm.c:61: undefined reference to `echo'
/src/nffm/nffm.c:62: undefined reference to `endwin'
nffm.o: In function `file_open':
/src/nffm/nffm.c:233: undefined reference to `echo'
nffm.o: In function `message':
/src/nffm/nffm.c:354: undefined reference to `wbkgd'
/src/nffm/nffm.c:355: undefined reference to `mvwprintw'
/src/nffm/nffm.c:356: undefined reference to `wrefresh'
/src/nffm/nffm.c:357: undefined reference to `wgetch'
/src/nffm/nffm.c:358: undefined reference to `werase'
/src/nffm/nffm.c:359: undefined reference to `wbkgd'
/src/nffm/nffm.c:360: undefined reference to `wrefresh'
nffm.o: In function `getNumber':
/src/nffm/nffm.c:468: undefined reference to `wgetch'
nffm.o: In function `reverseColor':
/src/nffm/nffm.c:479: undefined reference to `wattr_on'
/src/nffm/nffm.c:480: undefined reference to `wattr_on'
/src/nffm/nffm.c:481: undefined reference to `mvwprintw'
/src/nffm/nffm.c:482: undefined reference to `wrefresh'
/src/nffm/nffm.c:483: undefined reference to `wattr_off'
nffm.o: In function `normalColor':
/src/nffm/nffm.c:489: undefined reference to `mvwprintw'
/src/nffm/nffm.c:490: undefined reference to `wrefresh'
nffm.o: In function `displayList':
/src/nffm/nffm.c:497: undefined reference to `werase'
/src/nffm/nffm.c:500: undefined reference to `mvwprintw'
/src/nffm/nffm.c:502: undefined reference to `wrefresh'
nffm.o: In function `drawmenu':
/src/nffm/nffm.c:511: undefined reference to `werase'
/src/nffm/nffm.c:519: undefined reference to `wattr_on'
/src/nffm/nffm.c:520: undefined reference to `wattr_on'
/src/nffm/nffm.c:521: undefined reference to `mvwprintw'
/src/nffm/nffm.c:522: undefined reference to `wattr_off'
/src/nffm/nffm.c:523: undefined reference to `wattr_off'
/src/nffm/nffm.c:526: undefined reference to `wrefresh'
nffm.o: In function `refreshDirInfo':
/src/nffm/nffm.c:534: undefined reference to `werase'
/src/nffm/nffm.c:535: undefined reference to `mvwprintw'
/src/nffm/nffm.c:536: undefined reference to `mvwprintw'
/src/nffm/nffm.c:538: undefined reference to `mvwprintw'
/src/nffm/nffm.c:543: undefined reference to `wrefresh'
nffm.o: In function `refreshFileInfo':
/src/nffm/nffm.c:562: undefined reference to `mvwprintw'
/src/nffm/nffm.c:563: undefined reference to `mvwprintw'
/src/nffm/nffm.c:565: undefined reference to `mvwprintw'
/src/nffm/nffm.c:569: undefined reference to `mvwprintw'
/src/nffm/nffm.c:573: undefined reference to `mvwprintw'
/src/nffm/nffm.c:580: undefined reference to `wrefresh'
nffm.o: In function `deleteFile':
/src/nffm/nffm.c:676: undefined reference to `wbkgd'
/src/nffm/nffm.c:677: undefined reference to `mvwprintw'
/src/nffm/nffm.c:678: undefined reference to `wrefresh'
/src/nffm/nffm.c:679: undefined reference to `wgetch'
/src/nffm/nffm.c:681: undefined reference to `werase'
/src/nffm/nffm.c:687: undefined reference to `mvwprintw'
/src/nffm/nffm.c:690: undefined reference to `mvwprintw'
/src/nffm/nffm.c:693: undefined reference to `wrefresh'
/src/nffm/nffm.c:695: undefined reference to `werase'
/src/nffm/nffm.c:696: undefined reference to `wbkgd'
/src/nffm/nffm.c:697: undefined reference to `wrefresh'
nffm.o: In function `getUserText':
/src/nffm/nffm.c:712: undefined reference to `wbkgd'
/src/nffm/nffm.c:713: undefined reference to `mvwprintw'
/src/nffm/nffm.c:714: undefined reference to `wrefresh'
/src/nffm/nffm.c:719: undefined reference to `werase'
/src/nffm/nffm.c:720: undefined reference to `mvwprintw'
/src/nffm/nffm.c:721: undefined reference to `wrefresh'
/src/nffm/nffm.c:715: undefined reference to `wgetch'
/src/nffm/nffm.c:724: undefined reference to `werase'
/src/nffm/nffm.c:725: undefined reference to `wbkgd'
/src/nffm/nffm.c:726: undefined reference to `wrefresh'
nffm.o: In function `main':
/src/nffm/nffm.c:795: undefined reference to `initscr'
/src/nffm/nffm.c:796: undefined reference to `start_color'
/src/nffm/nffm.c:797: undefined reference to `init_pair'
/src/nffm/nffm.c:798: undefined reference to `init_pair'
/src/nffm/nffm.c:799: undefined reference to `init_pair'
/src/nffm/nffm.c:800: undefined reference to `init_pair'
/src/nffm/nffm.c:801: undefined reference to `stdscr'
/src/nffm/nffm.c:801: undefined reference to `stdscr'
/src/nffm/nffm.c:801: undefined reference to `stdscr'
/src/nffm/nffm.c:801: undefined reference to `stdscr'
/src/nffm/nffm.c:803: undefined reference to `newwin'
/src/nffm/nffm.c:804: undefined reference to `newwin'
/src/nffm/nffm.c:805: undefined reference to `newwin'
/src/nffm/nffm.c:806: undefined reference to `newwin'
/src/nffm/nffm.c:807: undefined reference to `newwin'
nffm.o:/src/nffm/nffm.c:808: more undefined references to `newwin' follow
nffm.o: In function `main':
/src/nffm/nffm.c:816: undefined reference to `wattr_on'
/src/nffm/nffm.c:817: undefined reference to `wattr_on'
/src/nffm/nffm.c:820: undefined reference to `keypad'
/src/nffm/nffm.c:821: undefined reference to `noecho'
/src/nffm/nffm.c:838: undefined reference to `wgetch'
/src/nffm/nffm.c:979: undefined reference to `werase'
/src/nffm/nffm.c:980: undefined reference to `wrefresh'
/src/nffm/nffm.c:1049: undefined reference to `werase'
/src/nffm/nffm.c:1050: undefined reference to `mvwprintw'
/src/nffm/nffm.c:1051: undefined reference to `wrefresh'
/src/nffm/nffm.c:1053: undefined reference to `echo'
/src/nffm/nffm.c:1054: undefined reference to `endwin'
collect2: ld returned 1 exit status
make: *** [nffm] Error 1
```

I have the libncurses5-dev package installed, but I don't know enough to track down the cause of the error. Thanks.

**Comment by mariostg** [comment]
Don't know about libncurses5-dev.  You probably need libncurses5 (http://packages.debian.org/squeeze/libncurses5).
If you cannot find ncurses.h on your system (/usr/include/ncurses.h in Archlinux)  that could be your problem.

**Comment by jieglen** [comment]
Nope, I've got /usr/include/ncurses.h (and libncurses5). It's a
strange error, because it does look like it can't find the library,
but it really looks like the library is there. Maybe there's a
different version within the library? That doesn't seem likely either.

I saw nffm on onethingwell, and I was hoping to see if it would be
useable to output the "selected files" to a pipe. I've got a little
playlist making script, and I've been looking for an easy way to
select files to send into it. nffm looked like it might fit the bill
with a bit of modification.

thanks,
Jeremy

On Wed, Jul 18, 2012 at 4:35 PM, mariostg
reply@reply.github.com
wrote:

**Comment by mariostg** [comment]
Did you include -lncurses in your compile command : gcc  nffm.c -lncurses -o nffm ?

Your idea of piping seems interesting.  It might give me some ideas.  Actually in nffm, there is a debug function called logger I use to direct any desired string to /tmp/log.txt.  Something could definitely be done with this.

**Comment by jieglen** [comment]
Interesting -- that command to compile: "gcc  nffm.c -lncurses -o
nffm" works! Using make does not -- so maybe there's something in the
Makefile?

On Thu, Jul 19, 2012 at 4:32 PM, mariostg
reply@reply.github.com
wrote:

**Comment by mariostg** [comment]
What are the first two lines of output from make?
I get that:
make
gcc -g -c nffm.c -o nffm.o
gcc -g -lncurses nffm.o -o nffm

**Comment by jieglen** [comment]
Same here -- it's after linking the object file that all of the errors happen.

Here's the full output after > make
gcc -g -c nffm.c -o nffm.o
gcc -g -lncurses nffm.o -o nffm
nffm.o: In function `DoDirectoryList':
/home/jeremy/src/nffm/nffm.c:61: undefined reference to`echo'
/home/jeremy/src/nffm/nffm.c:62: undefined reference to `endwin'
nffm.o: In function`file_open':
/home/jeremy/src/nffm/nffm.c:233: undefined reference to `echo'
nffm.o: In function`message':
/home/jeremy/src/nffm/nffm.c:354: undefined reference to `wbkgd'
/home/jeremy/src/nffm/nffm.c:355: undefined reference to`mvwprintw'
/home/jeremy/src/nffm/nffm.c:356: undefined reference to `wrefresh'
/home/jeremy/src/nffm/nffm.c:357: undefined reference to`wgetch'
/home/jeremy/src/nffm/nffm.c:358: undefined reference to `werase'
/home/jeremy/src/nffm/nffm.c:359: undefined reference to`wbkgd'
/home/jeremy/src/nffm/nffm.c:360: undefined reference to `wrefresh'
nffm.o: In function`getNumber':
/home/jeremy/src/nffm/nffm.c:468: undefined reference to `wgetch'
nffm.o: In function`reverseColor':
/home/jeremy/src/nffm/nffm.c:479: undefined reference to `wattr_on'
/home/jeremy/src/nffm/nffm.c:480: undefined reference to`wattr_on'
/home/jeremy/src/nffm/nffm.c:481: undefined reference to `mvwprintw'
/home/jeremy/src/nffm/nffm.c:482: undefined reference to`wrefresh'
/home/jeremy/src/nffm/nffm.c:483: undefined reference to `wattr_off'
nffm.o: In function`normalColor':
/home/jeremy/src/nffm/nffm.c:489: undefined reference to `mvwprintw'
/home/jeremy/src/nffm/nffm.c:490: undefined reference to`wrefresh'
nffm.o: In function `displayList':
/home/jeremy/src/nffm/nffm.c:497: undefined reference to`werase'
/home/jeremy/src/nffm/nffm.c:500: undefined reference to `mvwprintw'
/home/jeremy/src/nffm/nffm.c:502: undefined reference to`wrefresh'
nffm.o: In function `drawmenu':
/home/jeremy/src/nffm/nffm.c:511: undefined reference to`werase'
/home/jeremy/src/nffm/nffm.c:519: undefined reference to `wattr_on'
/home/jeremy/src/nffm/nffm.c:520: undefined reference to`wattr_on'
/home/jeremy/src/nffm/nffm.c:521: undefined reference to `mvwprintw'
/home/jeremy/src/nffm/nffm.c:522: undefined reference to`wattr_off'
/home/jeremy/src/nffm/nffm.c:523: undefined reference to `wattr_off'
/home/jeremy/src/nffm/nffm.c:526: undefined reference to`wrefresh'
nffm.o: In function `refreshDirInfo':
/home/jeremy/src/nffm/nffm.c:534: undefined reference to`werase'
/home/jeremy/src/nffm/nffm.c:535: undefined reference to `mvwprintw'
/home/jeremy/src/nffm/nffm.c:536: undefined reference to`mvwprintw'
/home/jeremy/src/nffm/nffm.c:538: undefined reference to `mvwprintw'
/home/jeremy/src/nffm/nffm.c:543: undefined reference to`wrefresh'
nffm.o: In function `refreshFileInfo':
/home/jeremy/src/nffm/nffm.c:562: undefined reference to`mvwprintw'
/home/jeremy/src/nffm/nffm.c:563: undefined reference to `mvwprintw'
/home/jeremy/src/nffm/nffm.c:565: undefined reference to`mvwprintw'
/home/jeremy/src/nffm/nffm.c:569: undefined reference to `mvwprintw'
/home/jeremy/src/nffm/nffm.c:573: undefined reference to`mvwprintw'
/home/jeremy/src/nffm/nffm.c:580: undefined reference to `wrefresh'
nffm.o: In function`deleteFile':
/home/jeremy/src/nffm/nffm.c:676: undefined reference to `wbkgd'
/home/jeremy/src/nffm/nffm.c:677: undefined reference to`mvwprintw'
/home/jeremy/src/nffm/nffm.c:678: undefined reference to `wrefresh'
/home/jeremy/src/nffm/nffm.c:679: undefined reference to`wgetch'
/home/jeremy/src/nffm/nffm.c:681: undefined reference to `werase'
/home/jeremy/src/nffm/nffm.c:687: undefined reference to`mvwprintw'
/home/jeremy/src/nffm/nffm.c:690: undefined reference to `mvwprintw'
/home/jeremy/src/nffm/nffm.c:693: undefined reference to`wrefresh'
/home/jeremy/src/nffm/nffm.c:695: undefined reference to `werase'
/home/jeremy/src/nffm/nffm.c:696: undefined reference to`wbkgd'
/home/jeremy/src/nffm/nffm.c:697: undefined reference to `wrefresh'
nffm.o: In function`getUserText':
/home/jeremy/src/nffm/nffm.c:712: undefined reference to `wbkgd'
/home/jeremy/src/nffm/nffm.c:713: undefined reference to`mvwprintw'
/home/jeremy/src/nffm/nffm.c:714: undefined reference to `wrefresh'
/home/jeremy/src/nffm/nffm.c:719: undefined reference to`werase'
/home/jeremy/src/nffm/nffm.c:720: undefined reference to `mvwprintw'
/home/jeremy/src/nffm/nffm.c:721: undefined reference to`wrefresh'
/home/jeremy/src/nffm/nffm.c:715: undefined reference to `wgetch'
/home/jeremy/src/nffm/nffm.c:724: undefined reference to`werase'
/home/jeremy/src/nffm/nffm.c:725: undefined reference to `wbkgd'
/home/jeremy/src/nffm/nffm.c:726: undefined reference to`wrefresh'
nffm.o: In function `main':
/home/jeremy/src/nffm/nffm.c:795: undefined reference to`initscr'
/home/jeremy/src/nffm/nffm.c:796: undefined reference to `start_color'
/home/jeremy/src/nffm/nffm.c:797: undefined reference to`init_pair'
/home/jeremy/src/nffm/nffm.c:798: undefined reference to `init_pair'
/home/jeremy/src/nffm/nffm.c:799: undefined reference to`init_pair'
/home/jeremy/src/nffm/nffm.c:800: undefined reference to `init_pair'
/home/jeremy/src/nffm/nffm.c:801: undefined reference to`stdscr'
/home/jeremy/src/nffm/nffm.c:801: undefined reference to `stdscr'
/home/jeremy/src/nffm/nffm.c:801: undefined reference to`stdscr'
/home/jeremy/src/nffm/nffm.c:801: undefined reference to `stdscr'
/home/jeremy/src/nffm/nffm.c:803: undefined reference to`newwin'
/home/jeremy/src/nffm/nffm.c:804: undefined reference to `newwin'
/home/jeremy/src/nffm/nffm.c:805: undefined reference to`newwin'
/home/jeremy/src/nffm/nffm.c:806: undefined reference to `newwin'
/home/jeremy/src/nffm/nffm.c:807: undefined reference to`newwin'
nffm.o:/home/jeremy/src/nffm/nffm.c:808: more undefined references to
`newwin' follow
nffm.o: In function`main':
/home/jeremy/src/nffm/nffm.c:816: undefined reference to `wattr_on'
/home/jeremy/src/nffm/nffm.c:817: undefined reference to`wattr_on'
/home/jeremy/src/nffm/nffm.c:820: undefined reference to `keypad'
/home/jeremy/src/nffm/nffm.c:821: undefined reference to`noecho'
/home/jeremy/src/nffm/nffm.c:838: undefined reference to `wgetch'
/home/jeremy/src/nffm/nffm.c:979: undefined reference to`werase'
/home/jeremy/src/nffm/nffm.c:980: undefined reference to `wrefresh'
/home/jeremy/src/nffm/nffm.c:1049: undefined reference to`werase'
/home/jeremy/src/nffm/nffm.c:1050: undefined reference to `mvwprintw'
/home/jeremy/src/nffm/nffm.c:1051: undefined reference to`wrefresh'
/home/jeremy/src/nffm/nffm.c:1053: undefined reference to `echo'
/home/jeremy/src/nffm/nffm.c:1054: undefined reference to`endwin'
collect2: ld returned 1 exit status
make: **\* [nffm] Error 1

On Thu, Jul 19, 2012 at 7:23 PM, mariostg
reply@reply.github.com
wrote:

**Comment by mariostg** [comment]
Ok I think I got it.  Found the answer at page 17 of An Introduction to GCC.  It appears the libraries must be placed after the objects or source file which use it.  Makefile has been corrected accordingly.

**Comment by Ferii66** [comment]
Here

**Comment by Ferii66** [comment]
/

**Comment by Ferii66** [comment]
[nffm-master.zip](https://github.com/user-attachments/files/17611838/nffm-master.zip)
